var elem=[];
$(document).ready(function(){elem.body=$("body");elem.text=$("#text");elem.typist=$("#typist");elem.footer=$("footer");elem.wrapper=$("#wrapper");var a=new Date,b=a.getHours(),a=a.getMinutes();if(20==b&&30<=a||20<b||4>=b)elem.body.addClass("dark");jQuery.extend(jQuery.browser,{SafariMobile:navigator.userAgent.toLowerCase().match(/iP(hone|ad)/i)});$.browser.SafariMobile&&window.scrollTo(0,1);$.browser.SafariMobile||(elem.text.attr("placeholder",elem.text.attr("placeholder")+" Need help? Type: !help."),elem.text.focus(),
$("#form").submit(function(a){a.preventDefault();$("#submit",this).attr("disabled","disabled");$("#text",this).attr("readonly","readonly").addClass("fade");a=elem.text.val();$.post("interface.php",{text:a,ajax:!0},function(a){if("Error"!=a){var a=JSON.parse(a),b=[];if(a.title){var c=[],h=[],i;231<a.title.length?(h.adn=" "==a.title.substring(229,230)?229:230,i=a.url.split("/")[1],h.twitter=" "==a.title.substring(105,106)?105:106,c.adn=a.title.substr(0,h.adn)+"\u2026",c.twitter=a.title.substr(0,h.twitter)+
"\u2026"):107<a.title.length&&321>=a.title.length?(c.adn=a.title,i=a.url.split("/")[1],h.twitter=" "==a.title.substring(105,106)?105:106,c.twitter=a.title.substr(0,h.twitter)+"\u2026"):(c.adn=a.title,c.twitter=c.adn,i=a.url);b.adn=encodeURIComponent(c.adn);b.twitter="&text="+encodeURIComponent(c.twitter)}else b.twitter="",b.adn="";elem.body.append('<div class="dim"><div class="box"><input type="text" value="http://bs1.textlr.org/'+a.url+'" onclick="this.focus();this.select();" readonly="readonly" /><a href="'+a.url+'">See the uploaded text.</a><div id="share"><ul><li><a href="https://twitter.com/share?url=http://bs1.textlr.org/'+
a.url+b.twitter+'&via=Textlr" target="_blank">Twitter</a></li><li><a href="https://alpha.app.net/intent/post?text='+b.adn+" http://bs1.textlr.org/"+i+'">App.net</a></li></ul></div></div></div>');$("#url input").focus().select()}else alert("Error")})}),elem.text.bind("keydown",function(a){a.metaKey&&13==a.keyCode?$("#submit").click():a.metaKey&&a.altKey&&window.preview(!0)}),$(document).keyup(function(){0<$(".preview").length&&hidepreview()}));elem.text.keyup(function(){var a=$(this),b=a.getSelection().end,
b=(b=/!(\S+)$/.exec(this.value.slice(0,b)))?b[1]:null,d=["help","date","donate","commands","preview"];for(item in d)if(d[item]==b){var f=window[d[item]](),f=a.val().replace("!"+d[item],f);$(this).val(f)}})});
function preview(a){if(0==$(".preview").length&&0==$("#url").length){var b=elem.text.val();2<b.length&&(a||(b=b.replace(/!preview/,"")),b=Markdown(b),elem.typist.hide(),elem.footer.hide(),elem.wrapper.append("<article class='preview'>"+b+"</article>"),b=$(".preview").text(),a||elem.wrapper.append('<button onclick="hidepreview()" class="okay" id="donepreview">I\'m done previewing.</button>'),elem.wrapper.append("<div class='textinfo'><h3>Characters: <b>"+(b.length-1)+"</b></h3><h3>Words: <b>"+b.split(" ").length+
"</b></h3></div>"))}if(!a)return""}function hidepreview(){0<$(".preview").length&&(elem.typist.show(),elem.footer.show(),$(".preview").remove(),$(".textinfo").remove(),0<$("#donepreview").length&&$("#donepreview").remove(),elem.text.blur(),elem.text.focus())}function hidepopover(){elem.typist.show();elem.footer.show();elem.text.focus();$(".popover").remove()}function date(){return $.format.date(new Date,"M/d/yy")}function donate(){window.location="donate.html";return""}
function commands(){elem.text.blur();elem.typist.hide();elem.footer.hide();elem.wrapper.append('<section id="commands" class="popover"><h1>Extendsorize.</h1><h2>Textlr has a lot <code>!commands</code> that will make using Textlr even more awesome.</h2><ul><li><h3><code>!help</code></h3><p>Brings up the <a href="javascript:hidepopover();help();">help</a> page.</p></li><li><h3><code>!commands</code></h3><p>Brings up this page</p></li><li><h3><code>!date</code></h3><p>Inserts the current date into the text in the format: <code>M/d/yy</code>. For example <em>October 8, 2012</em> would become <em>10/8/12</em>.</p></li><li><h3><code>!preview</code></h3><p>Pulls up the preview UI that is normally pulled up by \u2318\u2325 (cmd+alt). (Useful when on a moble device.)</p></li><li><h3><code>!donate</code></h3><p>Redirects to the <a href="donate.html">donation page</a>.</p></li></ul><h3>Am I missing something? <a href="mailto:hello@zyber17.com?subject=Textlr Commands">Email me</a>.</h3><h2 class="okay">Got it?</h2><button onclick="hidepopover();" class="okay">Got it.</button></section>');
return""}
function help(){elem.text.blur();elem.typist.hide();elem.footer.hide();elem.wrapper.append('<section id="help" class="popover"><h1>Have Some Help.</h1><h2>Textlr has a lot of cool features that you probably didn\'t know about. Here\'s how to use them.</h2><ul><li><h3>Markdown.</h3><p>All your documents will be parsed through <a href="http://daringfireball.net/projects/markdown/">Markdown</a>.</p></li><li><h3>Title your work.</h3><p>If you\'re a markdown user, you know that a line starting with <code>#</code> will become a first-level heading. If the first line of your document is a first level heading we automatically use it as title of your document. It\'s a as simple as that.</p><ul><li><h3>I don\'t want a title!</h3><p>Don\'t want your work to be titled but want your document to being with a first level heading? No worries, Just make the top line of your document empty.</p></li></ul></li><li><h3>Preview.</h3><p>Want to preview your document? Just press and hold \u2318\u2325 (cmd+alt) on a Mac. Theoretically it\'d be Ctrl+Alt on a PC but that\'s never been tested.</p></li><li><h3>Go out with a bang.</h3><p>Textlr supports <a href="javascript:hidepopover();commands();"><code>!commands</code></a> (said: "bang commands") that essentially are typing typing shortcuts. In fact you used one (<code>!help</code>) to get here! <a href="javascript:hidepopover();commands();">Here\'s a list of them.</a></p></li><li><h3>I wish I didn\'t have to move my mouse so far to click that "Upload" button.</h3><p>You don\'t! Just press \u2318\u21a9 (cmd+enter) when you want to submit on a Mac. Theoretically it\'d be Ctrl+Enter on a PC but that\'s never been tested.</p></li></ul><h2 class="okay">Got it?</h2><button onclick="hidepopover();" class="okay">Got it.</button></section>');return""}
(function(a){function b(a,b){var c=typeof a[b];return"function"===c||!!("object"==c&&a[b])||"unknown"==c}function c(a,b,c){0>b&&(b+=a.value.length);"undefined"==typeof c&&(c=b);0>c&&(c+=a.value.length);return{start:b,end:c}}function e(){return"object"==typeof document.body&&document.body?document.body:document.getElementsByTagName("body")[0]}var d,f,h,i,g,l,j,n,p;a(document).ready(function(){function m(a,b){return function(){var c=this.jquery?this[0]:this,d=c.nodeName.toLowerCase();if(1==c.nodeType&&
("textarea"==d||"input"==d&&"text"==c.type))if(c=[c].concat(Array.prototype.slice.call(arguments)),c=a.apply(this,c),!b)return c;if(b)return this}}var k=document.createElement("textarea");e().appendChild(k);if("undefined"!=typeof k.selectionStart&&"undefined"!=typeof k.selectionEnd)d=function(a){return{start:a.selectionStart,end:a.selectionEnd,length:a.selectionEnd-a.selectionStart,text:a.value.slice(a.selectionStart,a.selectionEnd)}},f=function(a,b,d){b=c(a,b,d);a.selectionStart=b.start;a.selectionEnd=
b.end},p=function(a,b){b?a.selectionEnd=a.selectionStart:a.selectionStart=a.selectionEnd};else if(b(k,"createTextRange")&&"object"==typeof document.selection&&document.selection&&b(document.selection,"createRange"))d=function(a){var b=0,c=0,d,e,f;if((f=document.selection.createRange())&&f.parentElement()==a)e=a.value.length,d=a.value.replace(/\r\n/g,"\n"),c=a.createTextRange(),c.moveToBookmark(f.getBookmark()),f=a.createTextRange(),f.collapse(!1),-1<c.compareEndPoints("StartToEnd",f)?b=c=e:(b=-c.moveStart("character",
-e),b+=d.slice(0,b).split("\n").length-1,-1<c.compareEndPoints("EndToEnd",f)?c=e:(c=-c.moveEnd("character",-e),c+=d.slice(0,c).split("\n").length-1));return{start:b,end:c,length:c-b,text:a.value.slice(b,c)}},f=function(a,b,d){var b=c(a,b,d),d=a.createTextRange(),e=b.start-(a.value.slice(0,b.start).split("\r\n").length-1);d.collapse(!0);b.start==b.end?d.move("character",e):(d.moveEnd("character",b.end-(a.value.slice(0,b.end).split("\r\n").length-1)),d.moveStart("character",e));d.select()},p=function(a,
b){var c=document.selection.createRange();c.collapse(b);c.select()};else{e().removeChild(k);window.console&&window.console.log&&window.console.log("TextInputs module for Rangy not supported in your browser. Reason: No means of finding text input caret position");return}e().removeChild(k);i=function(a,b,c,d){var e;b!=c&&(e=a.value,a.value=e.slice(0,b)+e.slice(c));d&&f(a,b,b)};h=function(a){var b=d(a);i(a,b.start,b.end,!0)};n=function(a){var b=d(a),c;b.start!=b.end&&(c=a.value,a.value=c.slice(0,b.start)+
c.slice(b.end));f(a,b.start,b.start);return b.text};g=function(a,b,c,d){var e=a.value;a.value=e.slice(0,c)+b+e.slice(c);d&&(b=c+b.length,f(a,b,b))};l=function(a,b){var c=d(a),e=a.value;a.value=e.slice(0,c.start)+b+e.slice(c.end);c=c.start+b.length;f(a,c,c)};j=function(a,b,c){var e=d(a),h=a.value;a.value=h.slice(0,e.start)+b+e.text+c+h.slice(e.end);b=e.start+b.length;f(a,b,b+e.length)};a.fn.extend({getSelection:m(d,!1),setSelection:m(f,!0),collapseSelection:m(p,!0),deleteSelectedText:m(h,!0),deleteText:m(i,
!0),extractSelectedText:m(n,!1),insertText:m(g,!0),replaceSelectedText:m(l,!0),surroundSelectedText:m(j,!0)})})})(jQuery);var MARKDOWN_VERSION="1.0.1o",MARKDOWNEXTRA_VERSION="1.2.5",MARKDOWN_EMPTY_ELEMENT_SUFFIX=" />",MARKDOWN_TAB_WIDTH=4,MARKDOWN_FN_LINK_TITLE="",MARKDOWN_FN_BACKLINK_TITLE="",MARKDOWN_FN_LINK_CLASS="",MARKDOWN_FN_BACKLINK_CLASS="",MARKDOWN_WP_POSTS=!0,MARKDOWN_WP_COMMENTS=!0;MARKDOWN_PARSER_CLASS="MarkdownExtra_Parser";
function Markdown(a){var b;"undefined"==typeof arguments.callee.parser?(b=eval("new "+MARKDOWN_PARSER_CLASS+"()"),b.init(),arguments.callee.parser=b):b=arguments.callee.parser;return b.transform(a)}
function Markdown_Parser(){this.nested_brackets_depth=6;this.nested_url_parenthesis_depth=4;this.escape_chars="\\\\`*_{}[]()>#+-.!";this.document_gamut=[["stripLinkDefinitions",20],["runBasicBlockGamut",30]];this.block_gamut=[["doHeaders",10],["doHorizontalRules",20],["doLists",40],["doCodeBlocks",50],["doBlockQuotes",60]];this.span_gamut=[["parseSpan",-30],["doImages",10],["doAnchors",20],["doAutoLinks",30],["encodeAmpsAndAngles",40],["doItalicsAndBold",50],["doHardBreaks",60]];this.em_relist=[["",
"(?:(^|[^\\*])(\\*)(?=[^\\*])|(^|[^_])(_)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["*","((?:\\S|^)[^\\*])(\\*)(?!\\*)"],["_","((?:\\S|^)[^_])(_)(?!_)"]];this.strong_relist=[["","(?:(^|[^\\*])(\\*\\*)(?=[^\\*])|(^|[^_])(__)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["**","((?:\\S|^)[^\\*])(\\*\\*)(?!\\*)"],["__","((?:\\S|^)[^_])(__)(?!_)"]];this.em_strong_relist=[["","(?:(^|[^\\*])(\\*\\*\\*)(?=[^\\*])|(^|[^_])(___)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["***","((?:\\S|^)[^\\*])(\\*\\*\\*)(?!\\*)"],["___","((?:\\S|^)[^_])(___)(?!_)"]]}
Markdown_Parser.prototype.init=function(){function a(a,b){a=a[1];b=b[1];return a>b?1:a<b?-1:0}this.prepareItalicsAndBold();this.nested_brackets_re=this._php_str_repeat("(?:[^\\[\\]]+|\\[",this.nested_brackets_depth)+this._php_str_repeat("\\])*",this.nested_brackets_depth);this.nested_url_parenthesis_re=this._php_str_repeat("(?:[^\\(\\)\\s]+|\\(",this.nested_url_parenthesis_depth)+this._php_str_repeat("(?:\\)))*",this.nested_url_parenthesis_depth);for(var b=[],c=0;c<this.escape_chars.length;c++)b.push(this._php_preg_quote(this.escape_chars.charAt(c)));
this.escape_chars_re="["+b.join("")+"]";this.empty_element_suffix=MARKDOWN_EMPTY_ELEMENT_SUFFIX;this.tab_width=MARKDOWN_TAB_WIDTH;this.no_entities=this.no_markup=!1;this.predef_urls={};this.predef_titles={};this.document_gamut.sort(a);this.block_gamut.sort(a);this.span_gamut.sort(a);this.urls={};this.titles={};this.html_hashes={};this.in_anchor=!1};Markdown_Parser.prototype.__wrapSTXETX__=function(a){"\u0002"!=a.charAt(0)&&(a="\u0002"+a);"\u0003"!=a.charAt(a.length-1)&&(a+="\u0003");return a};
Markdown_Parser.prototype.__unwrapSTXETX__=function(a){"\u0002"==a.charAt(0)&&(a=a.substr(1));"\u0003"==a.charAt(a.length-1)&&(a=a.substr(0,a.length-1));return a};Markdown_Parser.prototype._php_preg_quote=function(a){arguments.callee.sRE||(arguments.callee.sRE=/(\/|\.|\*|\+|\?|\||\(|\)|\[|\]|\{|\}\\)/g);return a.replace(arguments.callee.sRE,"\\$1")};Markdown_Parser.prototype._php_str_repeat=function(a,b){for(var c=a,e=1;e<b;e++)c+=a;return c};
Markdown_Parser.prototype._php_trim=function(a,b){var c=b||" \t\n\r";return a.replace(RegExp("^["+c+"]*|["+c+"]*$","g"),"")};Markdown_Parser.prototype._php_rtrim=function(a,b){return a.replace(RegExp("["+(b||" \t\n\r")+"]*$","g"),"")};Markdown_Parser.prototype._php_htmlspecialchars_ENT_NOQUOTES=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")};
Markdown_Parser.prototype.setup=function(){this.urls=this.predef_urls;this.titles=this.predef_titles;this.html_hashes={};this.in_anchor=!1};Markdown_Parser.prototype.teardown=function(){this.urls={};this.titles={};this.html_hashes={}};
Markdown_Parser.prototype.transform=function(a){this.setup();for(var a=a.replace(/^\xEF\xBB\xBF|\x1A/,""),a=a.replace(/\r\n?/,"\n",a),a=this.detab(a+"\n\n"),a=this.hashHTMLBlocks(a),a=a.replace(/^[ ]+$/m,""),b=0;b<this.document_gamut.length;b++){var c=this[this.document_gamut[b][0]];c?a=c.call(this,a):console.log(this.document_gamut[b][0]+" not implemented")}this.teardown();return a+"\n"};
Markdown_Parser.prototype.hashHTMLBlocks=function(a){if(this.no_markup)return a;var b=this.tab_width-1,c=this._php_str_repeat('(?:[^<]+|<\\2(?:\\s(?:[^>"/]+|/+(?!>)|"[^"]*"|\'[^\']*\')*)?(?:/>|>',4)+".*?"+this._php_str_repeat("</\\2\\s*>)|<(?!/\\2\\s*>))*",4),e=c.replace("\\2","\\3"),b=RegExp("(?:(?:(?:\\n\\n)|(?:\\x02)\\n?)([ ]{0,"+b+'}<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|address|script|noscript|form|fieldset|iframe|math)(?:\\s(?:[^>"/]+|/+(?!>)|"[^"]*"|\'[^\']*\')*)?>'+c+"</\\2>[ ]*(?=\\n+|\\n*\\x03)|[ ]{0,"+
b+'}<(ins|del)(?:\\s(?:[^>"/]+|/+(?!>)|"[^"]*"|\'[^\']*\')*)?>[ ]*\\n'+e+"</\\3>[ ]*(?=\\n+|\\n*\\x03)|[ ]{0,"+b+'}<(hr)(?:\\s(?:[^>"/]+|/+(?!>)|"[^"]*"|\'[^\']*\')*)?/?>[ ]*(?=\\n{2,}|\\n*\\x03)|[ ]{0,'+b+"}(?:<\!--.*?--\>)[ ]*(?=\\n{2,}|\\n*\\x03)|[ ]{0,"+b+"}(?:<([?%]).*?\\2>)[ ]*(?=\\n{2,}|\\n*\\x03)))","mig"),d=this,a=this.__wrapSTXETX__(a),a=a.replace(b,function(a,b){return"\n\n"+d.hashBlock(b)+"\n\n"});return a=this.__unwrapSTXETX__(a)};
Markdown_Parser.prototype.hashPart=function(a,b){"undefined"===typeof b&&(b="X");a=this.unhash(a);"undefined"===typeof arguments.callee.i&&(arguments.callee.i=0);var c=b+"\u001a"+ ++arguments.callee.i+b;this.html_hashes[c]=a;return c};Markdown_Parser.prototype.hashBlock=function(a){return this.hashPart(a,"B")};
Markdown_Parser.prototype.stripLinkDefinitions=function(a){var b=this.tab_width-1,c=this,a=this.__wrapSTXETX__(a),a=a.replace(RegExp("^[ ]{0,"+b+'}\\[(.+)\\][ ]?:[ ]*\\n?[ ]*(?:<(.+?)>|(\\S+?))[ ]*\\n?[ ]*(?:["\\(](.*?)["\\)][ ]*)?(?:\\n+|\\n*(?=\\x03))',"mg"),function(a,b,f,h,i){a=b.toLowerCase();c.urls[a]=f?f:h;c.titles[a]=i;return""});return a=this.__unwrapSTXETX__(a)};Markdown_Parser.prototype.runBlockGamut=function(a){a=this.hashHTMLBlocks(a);return this.runBasicBlockGamut(a)};
Markdown_Parser.prototype.runBasicBlockGamut=function(a){for(var b=0;b<this.block_gamut.length;b++){var c=this[this.block_gamut[b][0]];c?a=c.call(this,a):console.log(this.block_gamut[b][0]+" not implemented")}return a=this.formParagraphs(a)};Markdown_Parser.prototype.doHorizontalRules=function(a){var b=this;return a.replace(RegExp("^[ ]{0,3}([-\\*_])(?:[ ]{0,2}\\1){2,}[ ]*$","mg"),function(){return"\n"+b.hashBlock("<hr"+b.empty_element_suffix)+"\n"})};
Markdown_Parser.prototype.runSpanGamut=function(a){for(var b=0;b<this.span_gamut.length;b++){var c=this[this.span_gamut[b][0]];c?a=c.call(this,a):console.log(this.span_gamut[b][0]+" not implemented")}return a};Markdown_Parser.prototype.doHardBreaks=function(a){var b=this;return a.replace(/ {2,}\n/mg,function(){return b.hashPart("<br"+b.empty_element_suffix+"\n")})};
Markdown_Parser.prototype.doAnchors=function(a){if(this.in_anchor)return a;this.in_anchor=!0;var b=this,c=function(a,c,f,h){if("string"!==typeof h||""===h)h=f;h=h.toLowerCase();h=h.replace(/[ ]?\n/," ");"undefined"!==typeof b.urls[h]?(a=b.urls[h],a=b.encodeAttribute(a),a='<a href="'+a+'"',"undefined"!==typeof b.titles[h]&&(h=b.titles[h],h=b.encodeAttribute(h),a+=' title="'+h+'"'),f=b.runSpanGamut(f),a=b.hashPart(a+(">"+f+"</a>"))):a=c;return a},a=a.replace(RegExp("(\\[("+this.nested_brackets_re+")\\][ ]?(?:\\n[ ]*)?\\[(.*?)\\])",
"mg"),c),a=a.replace(RegExp("(\\[("+this.nested_brackets_re+")\\]\\([ \\n]*(?:<(.+?)>|("+this.nested_url_parenthesis_re+"))[ \\n]*((['\"])(.*?)\\6[ \\n]*)?\\))","mg"),function(a,c,f,h,i,g,l,j){f=b.runSpanGamut(f);a=b.encodeAttribute(h?h:i);a='<a href="'+a+'"';"undefined"!==typeof j&&""!==j&&(j=b.encodeAttribute(j),a+=' title="'+j+'"');f=b.runSpanGamut(f);return b.hashPart(a+(">"+f+"</a>"))}),a=a.replace(RegExp("(\\[([^\\[\\]]+)\\])","mg"),c);this.in_anchor=!1;return a};
Markdown_Parser.prototype.doImages=function(a){var b=this,a=a.replace(RegExp("(!\\[("+this.nested_brackets_re+")\\][ ]?(?:\\n[ ]*)?\\[(.*?)\\])","mg"),function(a,e,d,f){f=f.toLowerCase();if("string"!==typeof f||""===f)f=d.toLowerCase();d=b.encodeAttribute(d);"undefined"!==typeof b.urls[f]?(a='<img src="'+b.encodeAttribute(b.urls[f])+'" alt="'+d+'"',"undefined"!==typeof b.titles[f]&&(f=b.titles[f],f=b.encodeAttribute(f),a+=' title="'+f+'"'),a+=b.empty_element_suffix,a=b.hashPart(a)):a=e;return a});
return a=a.replace(RegExp("(!\\[("+this.nested_brackets_re+")\\]\\s?\\([ \\n]*(?:<(\\S*)>|("+this.nested_url_parenthesis_re+"))[ \\n]*((['\"])(.*?)\\6[ \\n]*)?\\))","mg"),function(a,e,d,f,h,i,g,l){a=f?f:h;d=b.encodeAttribute(d);a=b.encodeAttribute(a);d='<img src="'+a+'" alt="'+d+'"';"undefined"!==typeof l&&""!==l&&(l=b.encodeAttribute(l),d+=' title="'+l+'"');d+=b.empty_element_suffix;return b.hashPart(d)})};
Markdown_Parser.prototype.doHeaders=function(a){var b=this,a=a.replace(/^(.+?)[ ]*\n(=+|-+)[ ]*\n+/mg,function(a,e,d){if("-"==d&&e.match(/^-(?: |$)/))return a;a="="==d.charAt(0)?1:2;e="<h"+a+">"+b.runSpanGamut(e)+"</h"+a+">";return"\n"+b.hashBlock(e)+"\n\n"});return a=a.replace(RegExp("^(\\#{1,6})[ ]*(.+?)[ ]*\\#*\\n+","mg"),function(a,e,d){a=e.length;d="<h"+a+">"+b.runSpanGamut(d)+"</h"+a+">";return"\n"+b.hashBlock(d)+"\n\n"})};
Markdown_Parser.prototype.doLists=function(a){for(var b=this.tab_width-1,c=this,e=function(a,b,d,e,f){a=f.match("[\\*\\+-]")?"ul":"ol";b=c.processListItems(b+"\n","ul"==a?"[\\*\\+-]":"\\d+[\\.]");b=c.hashBlock("<"+a+">\n"+b+"</"+a+">");return"\n"+b+"\n\n"},d=[["[\\*\\+-]","\\d+[\\.]"],["\\d+[\\.]","[\\*\\+-]"]],f=0;f<d.length;f++)var h=d[f][0],h="((([ ]{0,"+b+"})("+h+")[ ]+)[\\s\\S]+?((?=\\x03)|\\n{2,}(?=\\S)(?![ ]*"+h+"[ ]+)|(?=\\n\\3"+d[f][1]+"[ ]+)))",a=this.__wrapSTXETX__(a),a=this.list_level?
a.replace(RegExp("^"+h,"mg"),e):a.replace(RegExp("(?:(?=\\n)\\n|\\x02\\n?)"+h,"mg"),e),a=this.__unwrapSTXETX__(a);return a};
Markdown_Parser.prototype.processListItems=function(a,b){"undefined"===typeof this.list_level&&(this.list_level=0);this.list_level++;var a=this.__wrapSTXETX__(a),a=a.replace(/\n{2,}(?=\x03)/m,"\n"),a=this.__unwrapSTXETX__(a),c=this,a=this.__wrapSTXETX__(a),a=a.replace(RegExp("(\\n)?([ ]*)("+b+"(?:[ ]+|(?=\\n)))([\\s\\S]*?)(?:(\\n+(?=\\n))|\\n)(?=\\n*(\\x03|\\2("+b+")(?:[ ]+|(?=\\n))))","gm"),function(a,b,f,h,i,g){b||g||i.match(/\n{2,}/)?(i=f+c._php_str_repeat(" ",h.length)+i,i=c.runBlockGamut(c.outdent(i)+
"\n")):(i=c.doLists(c.outdent(i)),i=i.replace(/\n+$/m,""),i=c.runSpanGamut(i));return"<li>"+i+"</li>\n"}),a=this.__unwrapSTXETX__(a);this.list_level--;return a};
Markdown_Parser.prototype.doCodeBlocks=function(a){var b=this,a=this.__wrapSTXETX__(a),a=a.replace(RegExp("(?:\\n\\n|(?=\\x02)\\n?)((?:^[ ]{"+this.tab_width+",}.*\\n+)+)((?=[ ]{0,"+this.tab_width+"}\\S)|(?:\\n*(?=\\x03)))","mg"),function(a,e){e=b.outdent(e);e=b._php_htmlspecialchars_ENT_NOQUOTES(e);e=b.__wrapSTXETX__(e);e=e.replace(/(?=\x02)\n+|\n+(?=\x03)/g,"");e=b.__unwrapSTXETX__(e);return"\n\n"+b.hashBlock("<pre><code>"+e+"\n</code></pre>")+"\n\n"});return a=this.__unwrapSTXETX__(a)};
Markdown_Parser.prototype.makeCodeSpan=function(a){a=this._php_htmlspecialchars_ENT_NOQUOTES(this._php_trim(a));return this.hashPart("<code>"+a+"</code>")};
Markdown_Parser.prototype.prepareItalicsAndBold=function(){this.em_strong_prepared_relist={};for(var a=0;a<this.em_relist.length;a++)for(var b=this.em_relist[a][0],c=this.em_relist[a][1],e=0;e<this.strong_relist.length;e++){for(var d=this.strong_relist[e][0],f=this.strong_relist[e][1],h=[],i=0;i<this.em_strong_relist.length;i++){var g=this.em_strong_relist[i][1];b+d==this.em_strong_relist[i][0]&&h.push(g)}h.push(c);h.push(f);f=RegExp("("+h.join("|")+")");this.em_strong_prepared_relist["rx_"+b+d]=
f}};
Markdown_Parser.prototype.doItalicsAndBold=function(a){for(var b="",c="",e=!1,d=[""],f=[];;){var h=a.match(this.em_strong_prepared_relist["rx_"+b+c]);if(h){for(var a=RegExp.leftContext,i=RegExp.rightContext,g="",l=h[1],j=2;j<h.length;j+=2)if("undefined"!==typeof h[j]){g=h[j];l=h[j+1];break}d[0]+=a+g;token=l;a=i}else{for(d[0]+=a;0<f.length&&0<f[0].length;)d[1]+=f.shift(),d[0]+=d.shift();break}h=token.length;if(e)3==h?(f.shift(),i=d.shift(),i=this.runSpanGamut(i),i="<strong><em>"+i+"</em></strong>",d[0]+=
this.hashPart(i),c=b=""):(f[0]=this._php_str_repeat(token.charAt(0),3-h),h=2==h?"strong":"em",i=d[0],i=this.runSpanGamut(i),i="<"+h+">"+i+"</"+h+">",d[0]=this.hashPart(i),"strong"==h?c="":b=""),e=!1;else if(3==h)if(""!=b)for(g=0;2>g;++g)h=2==f.shift().length?"strong":"em",i=d.shift(),i=this.runSpanGamut(i),i="<"+h+">"+i+"</"+h+">",d[0]=this.hashPart(i),"strong"==h?c="":b="";else b=token.charAt(0),c=b+b,f.unshift(token),d.unshift(""),e=!0;else 2==h?""!=c?(1==f[0].length&&(d[1]+=f.shift(),d[0]+=d.shift()),
f.shift(),i=d.shift(),i=this.runSpanGamut(i),i="<strong>"+i+"</strong>",d[0]+=this.hashPart(i),c=""):(f.unshift(token),d.unshift(""),c=token):""!=b?1==f[0].length?(f.shift(),i=d.shift(),i=this.runSpanGamut(i),i="<em>"+i+"</em>",d[0]+=this.hashPart(i),b=""):d[0]+=token:(f.unshift(token),d.unshift(""),b=token)}return d[0]};
Markdown_Parser.prototype.doBlockQuotes=function(a){var b=this;return a=a.replace(RegExp("((?:^[ ]*>[ ]?.+\\n(.+\\n)*\\n*)+)","mg"),function(a,e){e=e.replace(/^[ ]*>[ ]?|^[ ]+$/mg,"");e=b.runBlockGamut(e);e=e.replace(/^/mg,"  ");e=e.replace(/(\\s*<pre>[\\s\\S]+?<\/pre>)/mg,function(a,b){return b=b.replace(/^  /m,"")});return"\n"+b.hashBlock("<blockquote>\n"+e+"\n</blockquote>")+"\n\n"})};
Markdown_Parser.prototype.formParagraphs=function(a){for(var a=this.__wrapSTXETX__(a),a=a.replace(/(?:\x02)\n+|\n+(?:\x03)/g,""),a=this.__unwrapSTXETX__(a),a=a.split(/\n{2,}/m),b=0;b<a.length;b++){var c=a[b];""!=c&&(c.match(/^B\x1A[0-9]+B$/)?(c=this.html_hashes[c],a[b]=c):(c=this.runSpanGamut(c),c=c.replace(/^([ ]*)/,"<p>"),c+="</p>",a[b]=this.unhash(c)))}return a.join("\n\n")};Markdown_Parser.prototype.encodeAttribute=function(a){a=this.encodeAmpsAndAngles(a);return a=a.replace(/"/g,"&quot;")};
Markdown_Parser.prototype.encodeAmpsAndAngles=function(a){a=this.no_entities?a.replace(/&/g,"&amp;"):a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/,"&amp;");return a=a.replace(/</g,"&lt;")};
Markdown_Parser.prototype.doAutoLinks=function(a){var b=this,a=a.replace(/<((https?|ftp|dict):[^'">\s]+)>/i,function(a,e){var d=b.encodeAttribute(e);return b.hashPart('<a href="'+d+'">'+d+"</a>")});return a=a.replace(RegExp('<(?:mailto:)?((?:[-!#$%&\'*+/=?^_`.{|}~\\w\\x80-\\xFF]+|".*?")\\@(?:[-a-z0-9\\x80-\\xFF]+(\\.[-a-z0-9\\x80-\\xFF]+)*\\.[a-z]+|\\[[\\d.a-fA-F:]+\\]))>',"i"),function(a,e){var d=b.encodeEmailAddress(e);return b.hashPart(d)})};
Markdown_Parser.prototype.encodeEmailAddress=function(a){"undefined"===typeof arguments.callee.crctable&&(arguments.callee.crctable="00000000 77073096 EE0E612C 990951BA 076DC419 706AF48F E963A535 9E6495A3 0EDB8832 79DCB8A4 E0D5E91E 97D2D988 09B64C2B 7EB17CBD E7B82D07 90BF1D91 1DB71064 6AB020F2 F3B97148 84BE41DE 1ADAD47D 6DDDE4EB F4D4B551 83D385C7 136C9856 646BA8C0 FD62F97A 8A65C9EC 14015C4F 63066CD9 FA0F3D63 8D080DF5 3B6E20C8 4C69105E D56041E4 A2677172 3C03E4D1 4B04D447 D20D85FD A50AB56B 35B5A8FA 42B2986C DBBBC9D6 ACBCF940 32D86CE3 45DF5C75 DCD60DCF ABD13D59 26D930AC 51DE003A C8D75180 BFD06116 21B4F4B5 56B3C423 CFBA9599 B8BDA50F 2802B89E 5F058808 C60CD9B2 B10BE924 2F6F7C87 58684C11 C1611DAB B6662D3D 76DC4190 01DB7106 98D220BC EFD5102A 71B18589 06B6B51F 9FBFE4A5 E8B8D433 7807C9A2 0F00F934 9609A88E E10E9818 7F6A0DBB 086D3D2D 91646C97 E6635C01 6B6B51F4 1C6C6162 856530D8 F262004E 6C0695ED 1B01A57B 8208F4C1 F50FC457 65B0D9C6 12B7E950 8BBEB8EA FCB9887C 62DD1DDF 15DA2D49 8CD37CF3 FBD44C65 4DB26158 3AB551CE A3BC0074 D4BB30E2 4ADFA541 3DD895D7 A4D1C46D D3D6F4FB 4369E96A 346ED9FC AD678846 DA60B8D0 44042D73 33031DE5 AA0A4C5F DD0D7CC9 5005713C 270241AA BE0B1010 C90C2086 5768B525 206F85B3 B966D409 CE61E49F 5EDEF90E 29D9C998 B0D09822 C7D7A8B4 59B33D17 2EB40D81 B7BD5C3B C0BA6CAD EDB88320 9ABFB3B6 03B6E20C 74B1D29A EAD54739 9DD277AF 04DB2615 73DC1683 E3630B12 94643B84 0D6D6A3E 7A6A5AA8 E40ECF0B 9309FF9D 0A00AE27 7D079EB1 F00F9344 8708A3D2 1E01F268 6906C2FE F762575D 806567CB 196C3671 6E6B06E7 FED41B76 89D32BE0 10DA7A5A 67DD4ACC F9B9DF6F 8EBEEFF9 17B7BE43 60B08ED5 D6D6A3E8 A1D1937E 38D8C2C4 4FDFF252 D1BB67F1 A6BC5767 3FB506DD 48B2364B D80D2BDA AF0A1B4C 36034AF6 41047A60 DF60EFC3 A867DF55 316E8EEF 4669BE79 CB61B38C BC66831A 256FD2A0 5268E236 CC0C7795 BB0B4703 220216B9 5505262F C5BA3BBE B2BD0B28 2BB45A92 5CB36A04 C2D7FFA7 B5D0CF31 2CD99E8B 5BDEAE1D 9B64C2B0 EC63F226 756AA39C 026D930A 9C0906A9 EB0E363F 72076785 05005713 95BF4A82 E2B87A14 7BB12BAE 0CB61B38 92D28E9B E5D5BE0D 7CDCEFB7 0BDBDF21 86D3D2D4 F1D4E242 68DDB3F8 1FDA836E 81BE16CD F6B9265B 6FB077E1 18B74777 88085AE6 FF0F6A70 66063BCA 11010B5C 8F659EFF F862AE69 616BFFD3 166CCF45 A00AE278 D70DD2EE 4E048354 3903B3C2 A7672661 D06016F7 4969474D 3E6E77DB AED16A4A D9D65ADC 40DF0B66 37D83BF0 A9BCAE53 DEBB9EC5 47B2CF7F 30B5FFE9 BDBDF21C CABAC28A 53B39330 24B4A3A6 BAD03605 CDD70693 54DE5729 23D967BF B3667A2E,C4614AB8,5D681B02,2A6F2B94,B40BBE37,C30C8EA1,5A05DF1B,2D02EF8D");
for(var b=arguments.callee.crctable,a="mailto:"+a,c=[],e=0;e<a.length;e++)c.push(a.charAt(e));for(var d=Math.floor(Math.abs(function(a){var c;c=-1;for(var d=0;d<a.length;++d){var e=(c^a.charCodeAt(d))&255;c=c>>>8^"0x"+b[e]}return(c^-1)>>>0}(a)/a.length)),e=0;e<c.length;e++){var f=c[e],h=f.charCodeAt(0);if(128>h){var i=d*(1+e)%100;90<i&&"@"!=f||(c[e]=45>i?"&#x"+h.toString(16)+";":"&#"+h.toString(10)+";")}}a=c.join("");c=c.splice(7).join("");return'<a href="'+a+'">'+c+"</a>"};
Markdown_Parser.prototype.parseSpan=function(a){for(var b="",c=RegExp("(\\\\"+this.escape_chars_re+"|`+"+(this.no_markup?"":"|<\!--.*?--\>|<\\?.*?\\?>|<%.*?%>|<[/!$]?[-a-zA-Z0-9:_]+(?=\\s(?=[^\"'>]+|\"[^\"]*\"|'[^']*')*)?>")+")");;)if(a.match(c))RegExp.leftContext&&(b+=RegExp.leftContext),"`"==RegExp.lastMatch.charAt(0)&&"\\"==RegExp.leftContext.charAt(RegExp.leftContext.length-1)?(b+=RegExp.lastMatch,a=RegExp.rightContext):(a=this.handleSpanToken(RegExp.lastMatch,RegExp.rightContext),b+=a[0],a=a[1]);
else{b+=a;break}return b};Markdown_Parser.prototype.handleSpanToken=function(a,b){switch(a.charAt(0)){case "\\":return[this.hashPart("&#"+a.charCodeAt(1)+";"),b];case "`":if(b.match(RegExp("^([\\s\\S]*?[^`])"+this._php_preg_quote(a)+"(?!`)([\\s\\S]*)$","m"))){var c=RegExp.$1,b=RegExp.$2,c=this.makeCodeSpan(c);return[this.hashPart(c),b]}return[a,b];default:return[this.hashPart(a),b]}};Markdown_Parser.prototype.outdent=function(a){return a.replace(RegExp("^(\\t|[ ]{1,"+this.tab_width+"})","mg"),"")};
Markdown_Parser.prototype.detab=function(a){var b=this;return a.replace(/^.*\t.*$/mg,function(a){for(var e=a.split("\t"),a=e.shift(),d=0;d<e.length;d++)var f=e[d],a=a+(b._php_str_repeat(" ",b.tab_width-a.length%b.tab_width)+f);return a})};Markdown_Parser.prototype.unhash=function(a){var b=this;return a.replace(/(.)\x1A[0-9]+\1/g,function(a){return b.html_hashes[a]})};
function MarkdownExtra_Parser(){this.fn_id_prefix="";this.fn_link_title=MARKDOWN_FN_LINK_TITLE;this.fn_backlink_title=MARKDOWN_FN_BACKLINK_TITLE;this.fn_link_class=MARKDOWN_FN_LINK_CLASS;this.fn_backlink_class=MARKDOWN_FN_BACKLINK_CLASS;this.predef_abbr={};this.footnotes={};this.footnotes_ordered=[];this.abbr_desciptions={};this.abbr_word_re="";this.footnote_counter=1;this.block_tags_re="p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|address|form|fieldset|iframe|hr|legend";this.context_block_tags_re=
"script|noscript|math|ins|del";this.contain_span_tags_re="p|h[1-6]|li|dd|dt|td|th|legend|address";this.clean_tags_re="script|math";this.auto_close_tags_re="hr|img";this.em_relist=[["","(?:(^|[^\\*])(\\*)(?=[^\\*])|(^|[^a-zA-Z0-9_])(_)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["*","((?:\\S|^)[^\\*])(\\*)(?!\\*)"],["_","((?:\\S|^)[^_])(_)(?![a-zA-Z0-9_])"]];this.strong_relist=[["","(?:(^|[^\\*])(\\*\\*)(?=[^\\*])|(^|[^a-zA-Z0-9_])(__)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["**","((?:\\S|^)[^\\*])(\\*\\*)(?!\\*)"],
["__","((?:\\S|^)[^_])(__)(?![a-zA-Z0-9_])"]];this.em_strong_relist=[["","(?:(^|[^\\*])(\\*\\*\\*)(?=[^\\*])|(^|[^a-zA-Z0-9_])(___)(?=[^_]))(?=\\S|$)(?![\\.,:;]\\s)"],["***","((?:\\S|^)[^\\*])(\\*\\*\\*)(?!\\*)"],["___","((?:\\S|^)[^_])(___)(?![a-zA-Z0-9_])"]];this.escape_chars+=":|";this.document_gamut.push(["doFencedCodeBlocks",5]);this.document_gamut.push(["stripFootnotes",15]);this.document_gamut.push(["stripAbbreviations",25]);this.document_gamut.push(["appendFootnotes",50]);this.block_gamut.push(["doFencedCodeBlocks",
5]);this.block_gamut.push(["doTables",15]);this.block_gamut.push(["doDefLists",45]);this.span_gamut.push(["doFootnotes",5]);this.span_gamut.push(["doAbbreviations",70])}MarkdownExtra_Parser.prototype=new Markdown_Parser;
MarkdownExtra_Parser.prototype.setup=function(){this.constructor.prototype.setup.call(this);this.footnotes={};this.footnotes_ordered=[];this.abbr_desciptions={};this.abbr_word_re="";this.footnote_counter=1;for(var a in this.predef_abbr){var b=this.predef_abbr[a];""!=this.abbr_word_re&&(this.abbr_word_re+="|");this.abbr_word_re+=this._php_preg_quote(a);this.abbr_desciptions[a]=this._php_trim(b)}};
MarkdownExtra_Parser.prototype.teardown=function(){this.footnotes={};this.footnotes_ordered=[];this.abbr_desciptions={};this.abbr_word_re="";this.constructor.prototype.teardown.call(this)};MarkdownExtra_Parser.prototype.hashHTMLBlocks=function(a){return a=this._hashHTMLBlocks_inMarkdown(a)[0]};
MarkdownExtra_Parser.prototype._hashHTMLBlocks_inMarkdown=function(a,b,c,e){"undefined"===typeof b&&(b=0);"undefined"===typeof c&&(c="");"undefined"===typeof e&&(e=!1);if(""===a)return["",""];var d,f=/(?:^\n?|\n\n)*$/,h=/^([ ]*<\!--.*?--\>)?[ ]*\n/m,i=RegExp("(</?("+this.block_tags_re+"|"+this.context_block_tags_re+"|"+this.clean_tags_re+"|(?!\\s)"+c+")(?:(?=[\\s\"'/a-zA-Z0-9])(\".*?\"|'.*?'|.+?)*?)?>|<\!--.*?--\>|<\\?.*?\\?>|<%.*?%>|<!\\[CDATA\\[.*?\\]\\]>|`+"+(!e?"|(?:^[ ]*\\n|^|\\n[ ]*\\n)[ ]{"+
(b+4)+"}[^\\n]*\\n(?=(?:[ ]{"+(b+4)+"}[^\\n]*|[ ]*)\\n)*|(?:^|\\n)[ ]{0,"+b+"}~~~+[ ]*\\n":"")+")","m"),g=0,l="";do{var j=a.match(i),a=j?[RegExp.leftContext,RegExp.lastMatch,RegExp.rightContext]:[a];e&&(d=this.hashPart("",":"),a[0]=d+a[0].replace(/\n/g,d+"\n")+d);l+=a[0];if(!j){a="";break}j=a[1];a=a[2];d=this._php_preg_quote(j);if("`"==j.charAt(0))d=this._php_preg_quote(j),(d=a.match(RegExp("^(.+?|\\n[^\\n])*?[^`]"+d+"[^`]")))?(l+=j+d[0],a=a.substr(d[0].length)):l+=j;else if(j.match(RegExp("^\\n?[ ]{0,"+
NaN*(b+3))))d=this._php_preg_quote(this._php_trim(j)),(d=a.match(RegExp("^(?>.*\\n)+?[ ]{0,"+b+"}"+d+"[ ]*\\n")))?(l+=j+d[0],a=a.substr(d[0].length)):l+=j;else if("\n"==j.charAt(0)||" "==j.charAt(0))l+=j;else if(j.match(RegExp("^<(?:"+this.block_tags_re+")\\b"))||j.match(RegExp("^<(?:"+this.context_block_tags_re+")\\b"))&&l.match(f)&&a.match(h))a=this._hashHTMLBlocks_inHTML(j+a,this.hashBlock,!0),j=a[0],a=a[1],l+="\n\n"+j+"\n\n";else{if(j.match(RegExp("^<(?:"+this.clean_tags_re+")\\b"))||"!"==j.charAt(1)||
"?"==j.charAt(1))a=this._hashHTMLBlocks_inHTML(j+a,this.hashClean,!1),j=a[0],a=a[1];else if(""!==c&&j.match(RegExp("^</?(?:"+c+")\\b"))&&("/"==j.charAt(1)?g--:"/"!=j.charAr(j.length-2)&&g++,0>g)){a=j+a;break}l+=j}}while(0<=g);return[l,a]};
MarkdownExtra_Parser.prototype._hashHTMLBlocks_inHTML=function(a,b,c){if(""===a)return["",""];var e,d=/\s*markdown\s*=\s*(?:(["'])(.*?)\1|([^\s>]*))()/,f=RegExp("(</?[\\w:$]+(?:(?=[\\s\"'/a-zA-Z0-9])(?:\".*?\"|'.*?'|.+?)*?)?>|<\!--.*?--\>|<\\?.*?\\?>|<%.*?%>|<!\\[CDATA\\[.*?\\]\\]>)"),h=a,i=0,g="",l="",j="";if(e=a.match(/^<([\w:$]*)\b/))j=e[1];do{if(!a.match(f))return[h.charAt(0),h.substr(1)];var n=[RegExp.leftContext,RegExp.lastMatch,RegExp.rightContext],g=g+n[0];tag=n[1];a=n[2];if(tag.match(RegExp("^</?(?:"+
this.auto_close_tags_re+")\\b"))||"!"==tag.charAt(1)||"?"==tag.charAt(1))g+=tag;else{tag.match(RegExp("^</?"+j+"\\b"))&&("/"==tag.charAt(1)?i--:"/"!=tag.charAt(tag.length-2)&&i++);var p;c&&(p=tag.match(d))&&(p[2]+p[3]).match(/^1|block|span$/)?(tag=tag.replace(d,""),this.mode=p[2]+p[3],n="span"==this.mode||"block"!=this.mode&&tag.match(RegExp("^<(?:"+this.contain_span_tags_re+")\\b")),indent=(e=g.match(/(?:^|\n)( *?)(?! ).*?$/))?e[1].length:0,g+=tag,l+=b.call(this,g),e=tag.match(/^<([\w:$]*)\b/),a=
this._hashHTMLBlocks_inMarkdown(a,indent,e[1],n),g=a[0],a=a[1],0<indent&&(g=g.replace(RegExp("/^[ ]{1,"+indent+"}","m"),"")),l=n?l+g:l+("\n\n"+g+"\n\n"),g=""):g+=tag}}while(0<i);l+=b.call(this,g);return[l,a]};MarkdownExtra_Parser.prototype.hashClean=function(a){return this.hashPart(a,"C")};
MarkdownExtra_Parser.prototype.doHeaders=function(a){function b(a){return"undefined"===typeof a||""==a?"":' id="'+a+'"'}var c=this,a=a.replace(RegExp("(^.+?)(?:[ ]+\\{\\#([-_:a-zA-Z0-9]+)\\})?[ ]*\\n(=+|-+)[ ]*\\n+","mg"),function(a,d,f,h){if("-"==h&&d.match(/^- /))return a;a="="==h.charAt(0)?1:2;f=b(f);d="<h"+a+f+">"+c.runSpanGamut(d)+"</h"+a+">";return"\n"+c.hashBlock(d)+"\n\n"});return a=a.replace(RegExp("^(\\#{1,6})[ ]*(.+?)[ ]*\\#*(?:[ ]+\\{\\#([-_:a-zA-Z0-9]+)\\})?\\n+","mg"),function(a,d,f,
h){a=d.length;h=b(h);f="<h"+a+h+">"+c.runSpanGamut(f)+"</h"+a+">";return"\n"+c.hashBlock(f)+"\n\n"})};
MarkdownExtra_Parser.prototype.doTables=function(a){var b=this,c=this.tab_width-1,e=function(a,c,e,i){for(var c=c.replace(/[|] *$/m,""),e=e.replace(/[|] *$/m,""),i=i.replace(/[|] *$/m,""),a=[],g=e.split(/[ ]*[|][ ]*/),e=0;e<g.length;e++){var l=g[e];a[e]=l.match(/^ *-+: *$/)?' align="right"':l.match(/^ *:-+: *$/)?' align="center"':l.match(/^ *:-+ *$/)?' align="left"':""}c=b.parseSpan(c);l=c.split(/ *[|] */);c=l.length;g="<table>\n<thead>\n<tr>\n";for(e=0;e<l.length;e++)g+="  <th"+a[e]+">"+b.runSpanGamut(b._php_trim(l[e]))+
"</th>\n";g+="</tr>\n";g+="</thead>\n";i=b._php_trim(i,"\n").split("\n");g+="<tbody>\n";for(l=0;l<i.length;l++){for(var e=i[l],e=b.parseSpan(e),j=e.split(/ *[|] */,c);j.length<c;)j.push("");g+="<tr>\n";for(e=0;e<j.length;e++)g+="  <td"+a[e]+">"+b.runSpanGamut(b._php_trim(j[e]))+"</td>\n";g+="</tr>\n"}g+="</tbody>\n";g+="</table>";return b.hashBlock(g)+"\n"},a=this.__wrapSTXETX__(a),a=a.replace(RegExp("^[ ]{0,"+c+"}[|](.+)\\n[ ]{0,"+c+"}[|]([ ]*[-:]+[-| :]*)\\n((?:[ ]*[|].*\\n)*)(?=\\n|\\x03)","mg"),
function(a,b,c,i){i=i.replace(/^ *[|]/m,"");return e.call(this,a,b,c,i)}),a=a.replace(RegExp("^[ ]{0,"+c+"}(\\S.*[|].*)\\n[ ]{0,"+c+"}([-:]+[ ]*[|][-| :]*)\\n((?:.*[|].*\\n)*)(?=\\n|\\x03)","mg"),e);return a=this.__unwrapSTXETX__(a)};
MarkdownExtra_Parser.prototype.doDefLists=function(a){var b=this,c=this.tab_width-1,c="(?:(([ ]{0,"+c+"}((?:.*\\S.*\\n)+)\\n?[ ]{0,"+c+"}:[ ]+)([\\s\\S]+?)((?=\\0x03)|\\n{2,}(?=\\S)(?![ ]{0,"+c+"}(?:\\S.*\\n )+?\\n?[ ]{0,"+c+"}:[ ]+)(?![ ]{0,"+c+"}:[ ]+))))",a=this.__wrapSTXETX__(a),a=a.replace(RegExp("(\\x02\\n?|\\n\\n)"+c,"mg"),function(a,c,f){a=b._php_trim(b.processDefListItems(f));return c+b.hashBlock("<dl>\n"+a+"\n</dl>")+"\n\n"});return a=this.__unwrapSTXETX__(a)};
MarkdownExtra_Parser.prototype.processDefListItems=function(a){var b=this;less_than_tab=this.tab_width-1;a=this.__wrapSTXETX__(a);a=a.replace(/\n{2,}(?=\\x03)/,"\n");a=a.replace(RegExp("(\\x02\\n?|\\n\\n+)([ ]{0,"+less_than_tab+"}(?![:][ ]|[ ])(?:\\S.*\\n)+?)(?=\\n?[ ]{0,3}:[ ])","mg"),function(a,e,d){a=b._php_trim(d).split("\n");e="";for(d=0;d<a.length;d++)var f=a[d],f=b.runSpanGamut(b._php_trim(f)),e=e+("\n<dt>"+f+"</dt>");return e+"\n"});a=a.replace(RegExp("\\n(\\n+)?([ ]{0,"+less_than_tab+"}[:][ ]+)([\\s\\S]+?)(?=\\n+(?:[ ]{0,"+
less_than_tab+"}[:][ ]|<dt>|\\x03))","mg"),function(a,e,d,f){e||f.match(/\n{2,}/)?(f=b._php_str_repeat(" ",d.length)+f,f=b.runBlockGamut(b.outdent(f+"\n\n")),f="\n"+f+"\n"):(f=b._php_rtrim(f),f=b.runSpanGamut(b.outdent(f)));return"\n<dd>"+f+"</dd>\n"});return a=this.__unwrapSTXETX__(a)};
MarkdownExtra_Parser.prototype.doFencedCodeBlocks=function(a){var b=this,a=this.__wrapSTXETX__(a),a=a.replace(RegExp("(?:\\n|\\x02)(~{3,})[ ]*\\n((?:(?!\\1[ ]*\\n)[\\s\\S]*\\n+))\\1[ ]*\\n","mg"),function(a,e,d){d=b._php_htmlspecialchars_ENT_NOQUOTES(d);d=d.replace(/^\n+/,function(a){return b._php_str_repeat("<br"+b.empty_element_suffix,a.length)});return"\n\n"+b.hashBlock("<pre><code>"+d+"</code></pre>")+"\n\n"});return a=this.__unwrapSTXETX__(a)};
MarkdownExtra_Parser.prototype.formParagraphs=function(a){for(var a=this.__wrapSTXETX__(a),a=a.replace(/(?:\x02)\n+|\n+(?:\x03)/g,""),a=this.__unwrapSTXETX__(a),a=a.split(/\n{2,}/m),b=0;b<a.length;b++){var c=a[b];""!=c&&(c=this._php_trim(this.runSpanGamut(c)),c.match(/^B\x1A[0-9]+B|^C\x1A[0-9]+C$/)||(c="<p>"+c+"</p>"),a[b]=c)}a=a.join("\n\n");return a=this.unhash(a)};
MarkdownExtra_Parser.prototype.stripFootnotes=function(a){var b=this;return a=a.replace(RegExp("^[ ]{0,"+(this.tab_width-1)+"}\\[\\^(.+?)\\][ ]?:[ ]*\\n?((?:.+|\\n(?!\\[\\^.+?\\]:\\s)(?!\\n+[ ]{0,3}\\S))*)","mg"),function(a,e,d){b.footnotes[b.fn_id_prefix+e]=b.outdent(d);return""})};MarkdownExtra_Parser.prototype.doFootnotes=function(a){this.in_anchor||(a=a.replace(/\[\^(.+?)\]/g,"F\u001afn:$1\u001a:"));return a};
MarkdownExtra_Parser.prototype.appendFootnotes=function(a){var b=this,c=function(a,c){var d=b.fn_id_prefix+c;if(d in b.footnotes){b.footnotes_ordered.push([d,b.footnotes[d]]);delete b.footnotes[d];var e=b.footnote_counter++,f=' rel="footnote"';if(""!=b.fn_link_class)var h=b.fn_link_class,h=b.encodeAttribute(h),f=f+(' class="'+h+'"');""!=b.fn_link_title&&(h=b.fn_link_title,h=b.encodeAttribute(h),f+=' title="'+h+'"');f=f.replace(/%%/g,e);d=b.encodeAttribute(d);return'<sup id="fnref:'+d+'"><a href="#fn:'+
d+'"'+f+">"+e+"</a></sup>"}return"[^"+c+"]"},a=a.replace(/F\x1Afn:(.*?)\x1A:/g,c);if(0<this.footnotes_ordered.length){var a=a+'\n\n<div class="footnotes">\n',a=a+("<hr"+this.empty_element_suffix+"\n"),a=a+"<ol>\n\n",e=' rev="footnote"';if(""!=this.fn_backlink_class)var d=this.fn_backlink_class,d=this.encodeAttribute(d),e=e+(' class="'+d+'"');""!=this.fn_backlink_title&&(d=this.fn_backlink_title,d=this.encodeAttribute(d),e+=' title="'+d+'"');for(d=0;0<this.footnotes_ordered.length;)var f=this.footnotes_ordered.shift(),
h=f[0],f=f[1],f=f+"\n",f=this.runBlockGamut(f+"\n"),f=f.replace(/F\x1Afn:(.*?)\x1A:/g,c),e=e.replace(/%%/g,++d),h=this.encodeAttribute(h),i='<a href="#fnref:'+h+'"'+e+">&#8617;</a>",f=f.match(/<\/p>$/)?f.substr(0,f.length-4)+"&#160;"+i+"</p>":f+("\n\n<p>"+i+"</p>"),a=a+('<li id="fn:'+h+'">\n'),a=a+(f+"\n"),a=a+"</li>\n\n";a+="</ol>\n";a+="</div>"}return a};
MarkdownExtra_Parser.prototype.stripAbbreviations=function(a){var b=this;return a=a.replace(RegExp("^[ ]{0,"+(this.tab_width-1)+"}\\*\\[(.+?)\\][ ]?:(.*)","m"),function(a,e,d){""!=b.abbr_word_re&&(b.abbr_word_re+="|");b.abbr_word_re+=b._php_preg_quote(e);b.abbr_desciptions[e]=b._php_trim(d);return""})};
MarkdownExtra_Parser.prototype.doAbbreviations=function(a){var b=this;this.abbr_word_re&&(a=a.replace(RegExp("(^|[^\\w\\x1A])("+this.abbr_word_re+")(?![\\w\\x1A])"),function(a,e,d){if(d in b.abbr_desciptions){a=b.abbr_desciptions[d];if(!a||""==a)return b.hashPart("<abbr>"+d+"</abbr>");a=b.encodeAttribute(a);return b.hashPart('<abbr title="'+a+'">'+d+"</abbr>")}return a}));return a};this.Markdown=Markdown;this.Markdown_Parser=Markdown_Parser;this.MarkdownExtra_Parser=MarkdownExtra_Parser;
(function(a){var b="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),c="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),e="January February March April May June July August September October November December".split(" "),d=[];d.Jan="01";d.Feb="02";d.Mar="03";d.Apr="04";d.May="05";d.Jun="06";d.Jul="07";d.Aug="08";d.Sep="09";d.Oct="10";d.Nov="11";d.Dec="12";var f=function(a){var b="";-1!==a.indexOf(".")&&(b=a.split("."),a=b[0],b=b[1]);var c=a.split(":");return 3===c.length?
(hour=c[0],minute=c[1],second=c[2],{time:a,hour:hour,minute:minute,second:second,millis:b}):{time:"",hour:"",minute:"",second:"",millis:""}};a.format={date:function(a,i){try{var g=null,l=null,j=null,n=null,p=null,m=null;if("function"===typeof a.getFullYear)l=a.getFullYear(),j=a.getMonth()+1,n=a.getDate(),p=a.getDay(),m=f(a.toTimeString());else if(-1!=a.search(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.?\d{0,3}[-+]?\d{2}:?\d{2}/))var k=a.split(/[T\+-]/),l=k[0],j=k[1],n=k[2],m=f(k[3].split(".")[0]),g=new Date(l,
j-1,n),p=g.getDay();else switch(k=a.split(" "),k.length){case 6:l=k[5];j=d[k[1]]||k[1];n=k[2];m=f(k[3]);g=new Date(l,j-1,n);p=g.getDay();break;case 2:var q=k[0].split("-"),l=q[0],j=q[1],n=q[2],m=f(k[1]),g=new Date(l,j-1,n),p=g.getDay();break;case 7:case 9:case 10:l=k[3];j=d[k[1]]||k[1];n=k[2];m=f(k[4]);g=new Date(l,j-1,n);p=g.getDay();break;default:return a}k=g="";for(q=0;q<i.length;q++){var t=i.charAt(q),g=g+t;switch(g){case "ddd":k+=b[parseInt(p,10)]||p;g="";break;case "dd":if("d"==i.charAt(q+1))break;
1===String(n).length&&(n="0"+n);k+=n;g="";break;case "d":if("d"==i.charAt(q+1))break;k+=parseInt(n,10);g="";break;case "MMMM":var u=k,s=j,v=parseInt(s,10)-1,k=u+(e[v]||s),g="";break;case "MMM":if("M"===i.charAt(q+1))break;var u=k,s=j,w=parseInt(s,10)-1,k=u+(c[w]||s),g="";break;case "MM":if("M"==i.charAt(q+1))break;1===String(j).length&&(j="0"+j);k+=j;g="";break;case "M":if("M"==i.charAt(q+1))break;k+=j;g="";break;case "yyyy":k+=l;g="";break;case "yy":if("y"==i.charAt(q+1)&&"y"==i.charAt(q+2))break;
k+=String(l).slice(-2);g="";break;case "HH":k+=m.hour;g="";break;case "hh":var r=0==m.hour?12:13>m.hour?m.hour:m.hour-12,r=1==String(r).length?"0"+r:r,k=k+r,g="";break;case "h":if("h"==i.charAt(q+1))break;r=0==m.hour?12:13>m.hour?m.hour:m.hour-12;k+=parseInt(r,10);g="";break;case "mm":k+=m.minute;g="";break;case "ss":k+=m.second.substring(0,2);g="";break;case "SSS":k+=m.millis.substring(0,3);g="";break;case "a":k+=12<=m.hour?"PM":"AM";g="";break;case " ":k+=t;g="";break;case "/":k+=t;g="";break;case ":":k+=
t;g="";break;default:2===g.length&&0!==g.indexOf("y")&&"SS"!=g?(k+=g.substring(0,1),g=g.substring(1,2)):3===g.length&&-1===g.indexOf("yyy")&&(g="")}}return k}catch(x){return console.log(x),a}}}})(jQuery);jQuery.format.date.defaultShortDateFormat="dd/MM/yyyy";jQuery.format.date.defaultLongDateFormat="dd/MM/yyyy hh:mm:ss";
jQuery(document).ready(function(){jQuery(".shortDateFormat").each(function(a,b){jQuery(b).is(":input")?jQuery(b).val(jQuery.format.date(jQuery(b).val(),jQuery.format.date.defaultShortDateFormat)):jQuery(b).text(jQuery.format.date(jQuery(b).text(),jQuery.format.date.defaultShortDateFormat))});jQuery(".longDateFormat").each(function(a,b){jQuery(b).is(":input")?jQuery(b).val(jQuery.format.date(jQuery(b).val(),jQuery.format.date.defaultLongDateFormat)):jQuery(b).text(jQuery.format.date(jQuery(b).text(),
jQuery.format.date.defaultLongDateFormat))})});